### PR TITLE
Initial refactor to support backends

### PR DESCRIPTION
**Pull request by klimaj**
This PR provides an initial refactor to support multiple backends. Unit tests pass and no existing functionality was changed.

### CODE REVIEW

**Comment by ajasja** [comment]
Do the converters really need git and cloud pickle etc? Those should be installed by `python setup develop` then
image

**Comment by ajasja** [comment]
Not sure why this is getting pulled in by viewer3d...

**Comment by ajasja** [comment]
test notebook here, but you have to manually upload the ziped git repo. Maybe there is a better way to add git integration into google colab @weitzner ?
https://colab.research.google.com/drive/16sMs25Oh2ESZfISK5iw0NOOU1mwCjvBT?usp=sharing

**Comment by klimaj** [comment]
@ajasja Thanks for the review!

Re: converters - I was reusing existing validators from `pyrosetta.distributed.cluster.validators` but I see that importing `git` etc. - I've re-written the validators in `viewer3d.validators` to remove the dependency on `pyrosetta.distributed.cluster`

**Comment by klimaj** [comment]
Re: testing - I'm not sure about Google Colab, but for testing I am using Jupyter notebooks:

1. `cd pyrosetta_viewer3d/`
2. `git checkout <branch>`
3. `conda activate pyrosetta-dev`
4. `jupyter notebook`

In the jupyter notebook, I am testing with iPython magic:

```
import glob
import os
import pyrosetta
import pyrosetta.distributed.io as io
import tempfile
import unittest
import viewer3d

from IPython import get_ipython
from pyrosetta.rosetta.core.chemical import ResidueProperty
from pyrosetta.rosetta.core.select.residue_selector import (
    ChainSelector,
    ResiduePropertySelector,
    SecondaryStructureSelector,
)

ipython = get_ipython()
ipython.magic('load_ext autoreload')
ipython.magic('autoreload 2')
```
In a new cell:
```
poses = [io.pose_from_sequence("TEST" * i) for i in range(1, 4)]

view = (
    viewer3d.init(poses, (1200, 800.01), backend="py3Dmol") \
    + viewer3d.setStyle(style="line", colorscheme="magentaCarbon") \
    + viewer3d.setStyle(style="line", colorscheme="blackCarbon") \
    + viewer3d.setStyle(style="stick", colorscheme="greenCarbon") \
)
view.show()
```

**Comment by klimaj** [comment]
Re: Google Colab - can you use the `GitPython` module of some sort?:
```
import git
repo_clone_url = "git@github.com:mygithubuser/myrepo.git"
local_repo = "mytestproject"
repo = git.Repo.clone_from(repo_clone_url, local_repo)
repo.git.checkout('branchname')
```
with some combination of `pip install -e .`?

**Comment by klimaj** [comment]
Unit tests are still passing

**Review by ajasja — APPROVED** [review]
LGTM :)

**Comment by klimaj** [comment]
Thanks!

**Pull request merged**
