### PR TITLE
Support per-residue coloring by PerResidueRealMetrics in py3Dmol and nglview

### LINKED ISSUE #20: Viewer does not accept PDB file string
Example code:
```python
v = viewer3d.init("/mnt/net/shared/scaffolds/pre_scaffold_DB/tj_DHRs_filtered/X12_3_13_4_ct1_fe.pdb")
v.show()
```
image

### PR DESCRIPTION
**Pull request by klimaj**
The PR aims to address:
- Fixes #20 
- Supports element-based `'<color>Carbon'` color scheme inputs for `nglview` to match `py3Dmol` color scheme inputs
- Adds a new visualization module, `viewer3d.setPerResidueRealMetric`
- Adds features in #13 
  - `viewer3d.presets.perResidueEnergyMetric`
  - `viewer3d.presets.perResidueClashMetric`
  - `viewer3d.presets.perResidueSasaMetric`
  - `viewer3d.presets.unsatSelector`
- Adds a `viewer3d.presets.rosettaViewer` with an `IntSlider` to select presets:
        `0`: `perResidueEnergyMetric`
        `1`: `perResidueClashMetric`
        `2`: `perResidueSasaMetric` (fixed when scrolling back to it a second time)
        `3`: `unsatSelector`
        `4`: `ligandsAndMetals`
- Adds docstrings for documentation
- Fixes `README.md` formatting; adds examples
- Updates unit tests for new features
- Show bond valency by default in `nglview`

### CODE REVIEW

**Comment by klimaj** [comment]
@ajasja Please give these a try!
```
import bokeh.palettes
import pyrosetta
import pyrosetta.distributed.io as io
import viewer3d

from ipywidgets.widgets import Output

out = Output()
with out:
    pyrosetta.init()
    poses = [pyrosetta.io.pose_from_sequence("TEST" * i) for i in range(1, 6)]
    pose = pyrosetta.toolbox.rcsb.pose_from_rcsb("6V67")
```
```
scorefxn = pyrosetta.create_score_function("ref2015")
minimize = pyrosetta.rosetta.protocols.minimization_packing.MinMover()
e = (
    pyrosetta.rosetta.core.simple_metrics.per_residue_metrics.PerResidueEnergyMetric()
)
e.set_scorefunction(scorefxn)
v = viewer3d.init(backend=backend, gui=True)
palette = list(bokeh.palettes.Greens256) + list(
    reversed(bokeh.palettes.Reds256)
)
v += viewer3d.setStyle(radius=0)
v += viewer3d.setPerResidueRealMetric(
    scoretype="res_energy", vmin=-10, vmax=10, radius=0.2, log=10, palette=palette
)
v += viewer3d.setHydrogens(polar_only=True, color="lightgray")
v += viewer3d.setHydrogenBonds()
v += viewer3d.setDisulfides()
for h in range(10):
    _pose = pose.clone()
    _pose.scores.clear()
    for i in range(20):
        minimize.apply(_pose)
    e.apply(_pose)
    v.add_pose(_pose, index=h, update_viewer=False)
v.show()
```
```
viewer = viewer3d.presets.perResidueEnergyMetric(pose)
viewer.show()
```
```
viewer = viewer3d.presets.perResidueClashMetric(poses, backend=0)
viewer.show()
```
```
viewer = viewer3d.presets.perResidueSasaMetric(pose, backend=1)
viewer.show()
```
```
viewer = viewer3d.presets.unsatSelector(pose)
viewer.show()
```
```
viewer = viewer3d.presets.rosettaViewer(poses, backend=0) # backend=1
viewer.show()
```

**Comment by klimaj** [comment]
Example of `viewer3d.perResidueEnergyMetric` coloring (green are residues with <0 per-residue total score, red are residues with >0 per-residue total score):
Screen Shot 2022-07-09 at 12 29 16 PM

**Comment by klimaj** [comment]
Now fixed the `viewer3d.presets.perResidueSasaMetric` when scrolling back to it a second time in `py3Dmol`. I also added `viewer3d.presets.perResidueSasaMetric` to `viewer3d.presets.rosettaViewer` as preset `2`.

**Comment by ajasja** [comment]
Presets differ in default styles, which is unexpected. I would add the cartoon representation to py3dmol as well
image

nglview does not show the coloring in the notebook 
image

**Comment by ajasja** [comment]
For the rosettaViewer a dropdown would be much better than a slider
viewer = viewer3d.presets.rosettaViewer(poses, backend=0) # backend=1
viewer.show()

But I like the idea of combining them! 
image

Do you think there would be away to show a color scale bar with values for the energies and the SASA etc?

**Comment by ajasja** [comment]
Interestingly passing a string still does not work

```python
!wget https://files.rcsb.org/download/1atp.pdb1
viewer = viewer3d.init('1atp.pdb1')
viewer.show()
```

image

**Comment by klimaj** [comment]
@ajasja Re: passing a string still does not work - there appears to be an issue with the `--serialization` flag (not necessarily an issue with the viewer)

**Comment by klimaj** [comment]
@ajasja I've now updated:
-  added a cartoon representation to `py3Dmol` in the `viewer3d.setPerResidueRealMetrics`
- `viewer3d.presets.rosettaViewer` uses a dropdown menu to switch between different presets

Also, each of the presets are expected to differ in style a bit. New presets may always be added with matching styles if preferable. I'm still okay tweaking the styles of these presets if you have any suggestions!

**Comment by klimaj** [comment]
@ajasja I've also now implemented a colorbar for viewing the `viewer3d.setPerResidueRealMetric` modules. For example (click image for a high quality version):
Screen Shot 2022-07-30 at 9 54 50 PM

**Comment by klimaj** [comment]
Example of the `viewer3d.presets.rosettaViewer` preset dropdown menu also showing the colorbar:
Screen Shot 2022-07-30 at 10 02 10 PM

**Comment by ajasja** [comment]
Nice!

When I try to run this code:
```python
scorefxn = pyrosetta.create_score_function("ref2015")
minimize = pyrosetta.rosetta.protocols.minimization_packing.MinMover()
e = (
    pyrosetta.rosetta.core.simple_metrics.per_residue_metrics.PerResidueEnergyMetric()
)
e.set_scorefunction(scorefxn)
v = viewer3d.init(backend='py3Dmol', gui=True)
palette = list(bokeh.palettes.Greens256) + list(
    reversed(bokeh.palettes.Reds256)
)
v += viewer3d.setStyle(radius=0)
v += viewer3d.setPerResidueRealMetric(
    scoretype="res_energy", vmin=-10, vmax=10, radius=0.2, palette=palette
)
v += viewer3d.setHydrogens(polar_only=True, color="lightgray")
v += viewer3d.setHydrogenBonds()
#v += viewer3d.setDisulfides()
for h in range(10):
    _pose = pose.clone()
    _pose.scores.clear()
    for i in range(20):
        minimize.apply(_pose)
    e.apply(_pose)
    v.add_pose(_pose, index=h, update_viewer=False)
v.show()
```

I get 
`AttributeError: 'ListedColormap' object has no attribute 'with_extremes'`

image

**Comment by ajasja** [comment]
Installing matplotlib 3.5 fixes the problem, but we should add this to the requirements.

**Review by ajasja — APPROVED** [review]
Looks good to me!

**Comment by klimaj** [comment]
@ajasja thanks for the review! Also added `matplotlib` to `setup.py` dependencies, and updated the colorbar labels for the `rosettaViewer` presets:
Screen Shot 2022-08-31 at 10 46 25 PM

**Comment by ajasja** [comment]
Minor detail: 3.5.2 gives me an error with pip install on google colab
image
But 3.5 should be OK

**Comment by ajasja** [comment]
Hmm, well not really, I still have to install two things manually, but I'll open a separate PR when I figure it out:
```python
!pip install py3dmol nglview 
!pip install matplotlib==3.5
!python setup.py develop
```

**Pull request merged**
